# Generated by Django 6.1 on 2026-08-12 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of the Participant', max_length=150)),
                ('email', models.EmailField(help_text='Contact Email Address', max_length=254)),
                ('roll_number', models.CharField(help_text='Unique Roll / Registration Number', max_length=50, unique=True)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('attended', models.BooleanField(default=False, help_text='Attendance Status')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Timestamp when participant checked in', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
